kind: pipeline
type: docker
name: Apply Cloud infra changes

steps:
- name: Apply changes via Terraform
  environment:
    ARM_CLIENT_ID:
     from_secret: ARM_CLIENT_ID
    ARM_CLIENT_SECRET:
      from_secret: ARM_CLIENT_SECRET
    ARM_SUBSCRIPTION_ID:
      from_secret: ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID:
      from_secret: ARM_TENANT_ID
    CLOUDFLARE_EMAIL:
      from_secret: CLOUDFLARE_EMAIL
    CLOUDFLARE_API_TOKEN:
      from_secret: CLOUDFLARE_API_TOKEN
    ARTIFACTORY_USERNAME:
      from_secret: ARTIFACTORY_USERNAME
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_URL:
      from_secret: ARTIFACTORY_URL
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
  image: hashicorp/terraform
  commands:
  - terraform init
  - terraform validate
  - terraform import "azurerm_resource_group.rg-cosmostest-cosmosdb" "/subscriptions/1f0aad73-a560-419a-a3a1-e30d0dec98b3/resourceGroups/rg-cosmostest-cosmosdb"
  - terraform import "azurerm_resource_group.rg-hanyadikhet-functionapp" "/subscriptions/1f0aad73-a560-419a-a3a1-e30d0dec98b3/resourceGroups/rg-hanyadikhet-functionapp"
  - terraform import "azurerm_cosmosdb_account.cosmodb" "/subscriptions/1f0aad73-a560-419a-a3a1-e30d0dec98b3/resourceGroups/rg-cosmostest-cosmosdb/providers/Microsoft.DocumentDB/databaseAccounts/cosmosdbtorma"
  - terraform plan
  - terraform apply -auto-approve
